---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-02
spec:
  # Step 1: Define a custom parameter named "git_commit" of type string
  params:
    - name: git_commit
      type: string
  steps:
    - name: print-git-commit
      image: registry.access.redhat.com/ubi9/ubi:latest
      # Step 2: Use the "git_commit" parameter and print it
      script: |
        #!/bin/sh
        # Place for your code..

        echo "Git Commit: $(params.git_commit)"